image: irishblockade/tcm-pipeline:latest

pipelines:
  default:
    - step:
        deployment: production
        script: 
          - |
             echo "Hello World $PLACE" > motd.txt
             cat motd.txt | tr [:lower:] [:upper:]
