image: irishblockade/tcm-pipeline:latest

pipelines:
  default:
    - step:
        deployment: production
        script: 
          - |
             echo "Hello World $PLACE" | base64 > motd.txt 
             cat motd.txt | base64 --decode
